### ISSUE TITLE
Missing file game-settings.js

### ISSUE THREAD

**Issue by jpokrzyk** [GoogleCloudPlatform/cloud-derby#10]
`cloud/controller/js/game-settings.js` as described on **page 36** of [Cloud Derby Setup Instructions](https://docs.google.com/document/d/1PVv9Pstwpu9DWkVE05a4GN8UD90YD2sF53v1C8u6s3Q/edit#heading=h.cxb34nxgvh0m) is missing in this repo.

**Comment by jpokrzyk** [comment]
Oh I see the file is in the repo as `settings.js` and all the code references this file correctly. Looks like the doc just needs to be updated.

**Comment by romankhar** [comment]
This has been renamed into settings.sh. I also updated the tutorial to reflect this.
