### ISSUE TITLE
Training the model ends unsuccessfully (or at least with a warning)

### ISSUE THREAD

**Issue by jpokrzyk** [GoogleCloudPlatform/cloud-derby#11]
The command `cd $HOME/cloud-derby/cloud/ml/training/  &&  ./run.sh` from [Train a TensorFlow model](https://docs.google.com/document/d/1PVv9Pstwpu9DWkVE05a4GN8UD90YD2sF53v1C8u6s3Q/edit#heading=h.vlb25qgraqgp) ends unsuccessfully:
![Screenshot 2019-07-12 at 2 25 32 PM](https://user-images.githubusercontent.com/4333958/61151416-e6375d00-a4b3-11e9-94ea-a4f75bf1aa56.png)

**Comment by romankhar** [comment]
This is the output from tail -f, so this works as expected. Need to press CTRL-C to stop the output.
